context:
  name: renode-cli
  version: "1.16.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/releases/download/v${{ version }}/renode_${{ version }}_source.tar.xz
    sha256: fefe9a495cb54af09f13a93a863b6cad027f7ddc8854921efa6e42d9fbcd9888

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - dotnet >=9
    - nuget-license >=3.1
    - if: unix
      then:
        - sed
        - bash
      else:
        - m2-bash
        - m2-coreutils
        - m2-findutils
        - m2-sed
  host:
    - renode-cores ==${{ version }}
  run:
    - dotnet >=9

tests:
  - package_contents:
      strict: true
      bin:
        - renode
      files:
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}OptionsParser.deps.json
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}OptionsParser.runtimeconfig.json
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Renode${{ ".exe" if not unix }}
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Renode.deps.json
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Renode.runtimeconfig.json
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Sprache.xml
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}build_type
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}*.{dll,dylib,pdb,so}
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Lib/*.py
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Lib/site-packages/README.txt
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Lib/{ctypes,distutils,email,encodings,ensurepip}/*
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}Lib/{lib2to3,multiprocessing,unittest,wsgiref,xml}/*
        - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}{cs,de,es,fr,it,ja,ko,pl,ru,tr,zh-Hans,zh-Hant}/*.dll
        - ${{ "Library/" if not unix }}share/renode-cli/platforms/{boards,cpus}/*.repl
        - ${{ "Library/" if not unix }}share/renode-cli/scripts/monitor.py
        - ${{ "Library/" if not unix }}share/renode-cli/scripts/{complex,multi-node,single-node}/*
        - ${{ "Library/" if not unix }}share/renode-cli/scripts/pydev/*.py
        - ${{ "Library/" if not unix }}share/renode-cli/tools/sel4_extensions/*
        - if: unix
          then:
            - libexec/renode-cli/runtimes/*
            # Post-install tests
            - etc/conda/test-files/renode-cli/*
          else:
            - ${{ "Library/" if not unix }}libexec/renode-cli/${{ "Release/" if not unix }}testhost${{ ".exe" if not unix }}
  - script:
      - renode --help
      - LOCAL_TEST_PREFIX=./test-bundle test-bundle/${{ "Library/" if not unix }}bin/renode-test test-bundle/${{ "Library/" if not unix }}share/renode-cli/tests/unit-tests
    requirements:
      run:
        - robotframework >=6.1
        - psutil >=5.9.3
        - python
        - pyyaml >=6.0
    files:
      recipe:
        - test-bundle/

about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
    - danielnachun
