context:
  name: renode-cli
  version: "1.16.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/releases/download/v${{ version }}/renode_${{ version }}_source.tar.xz
    sha256: fefe9a495cb54af09f13a93a863b6cad027f7ddc8854921efa6e42d9fbcd9888

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - dotnet >=9
    - nuget-license >=3.1
    - if: unix
      then:
        - sed
        - bash
      else:
        - m2-bash
        - m2-coreutils
        - m2-findutils
        - m2-sed
  host:
    - renode-cores ==${{ version }}
  run:
    - dotnet >=9

tests:
  - package_contents:
      strict: true
      bin:
        - renode
      files:
        - ${{ "Library/" if win }}libexec/renode-cli/Renode
        - ${{ "Library/" if win }}libexec/renode-cli/Renode.deps.json
        - ${{ "Library/" if win }}libexec/renode-cli/Renode.runtimeconfig.json
        - ${{ "Library/" if win }}libexec/renode-cli/Sprache.xml
        - ${{ "Library/" if win }}libexec/renode-cli/build_type
        - ${{ "Library/" if win }}libexec/renode-cli/*.{dll,pdb,so}
        - ${{ "Library/" if win }}libexec/renode-cli/Lib/README.txt
        - ${{ "Library/" if win }}libexec/renode-cli/Lib/*.py
        - ${{ "Library/" if win }}libexec/renode-cli/Lib/site-package/README.txt
        - ${{ "Library/" if win }}libexec/renode-cli/Lib/{ctypes,distutils,email,encodings,ensurepip}/*
        - ${{ "Library/" if win }}libexec/renode-cli/Lib/{lib2to3,multiprocessing,unittest,wsgiref,xml}/*
        - ${{ "Library/" if win }}libexec/renode-cli/{cs,de,es,fr,it,ja,ko,pl,ru,tr,zh-Hans,zh-Hant}/*.dll
        - ${{ "Library/" if win }}libexec/renode-cli/runtimes/*
        - ${{ "Library/" if win }}share/renode-cli/platforms/{boards,cpus}/*.repl
        - ${{ "Library/" if win }}share/renode-cli/scripts/monitor.py
        - ${{ "Library/" if win }}share/renode-cli/scripts/{complex,multi-node,single-node}/*
        - ${{ "Library/" if win }}share/renode-cli/scripts/pydev/*.py
        - ${{ "Library/" if win }}share/renode-cli/tools/sel4_extensions/*
        # Post-install tests
        - etc/conda/test-files/renode-cli/*
  - script:
      - if: unix
        then:
          - renode --help
          - LOCAL_TEST_PREFIX=./test-bundle test-bundle/${{ "Library/" if win }}bin/renode-test test-bundle/${{ "Library/" if win }}share/renode-cli/tests/unit-tests
        else:
          - echo "Skip: Dodgy Access denied from dotnet file lock?"
    requirements:
      run:
        - robotframework >=6.1
        - psutil >=5.9.3
        - python
        - pyyaml >=6.0
    files:
      recipe:
        - test-bundle/

about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
    - danielnachun
